log_path: /home/sebastien/Documents/IPSDK/IMAGE/thomas/
debug: true
PLANT_MODEL: banana
csv_file: /home/sebastien/Documents/IPSDK/IMAGE/thomas/IPSDK_inocTHOMAS_Rep1.csv
rename:
- projet
- position
RUNSTEP:
    draw: false
    crop: true
    ML: true
    merge: true
DRAWCROP:
    images_path: /home/sebastien/Documents/IPSDK/IMAGE/thomas
    out_cut_dir: /home/sebastien/Documents/IPSDK/IMAGE/thomas/crop
    out_draw_dir: /home/sebastien/Documents/IPSDK/IMAGE/thomas/draw
    extension: tif
    x_pieces: 2
    y_pieces: 3
    top: 80
    left: 120
    right: 120
    bottom: 80
    noise_remove: false
    numbering: Bottom
    force_rerun: false
ML:
    images_path: /home/sebastien/Documents/IPSDK/IMAGE/thomas/crop
    model_name: test_thomas
    model_name_classification: banana_trips
    split_ML: false
    calibration_name:
    small_object: 30
    alpha: 0.8
    leaf_border: 80
    noise_remove: false
    force_rerun: true
    draw_ML_image: true
MERGE:
    rm_original: true
    extension: jpg
